### ISSUE TITLE
idx_phiZ index out of range when GNsize > bsize

### ISSUE THREAD

**Issue by andy920262** [cjlin1/simpleNN#11]
I find 29th line in vTP.m will throw an error when I run NewtonCG with full MNIST dataset.
```
idx = net.idx_phiZ{m}(:, 1:num_v);
```
the second dim of `idx_phiZ` is `nL * bsize`, but `num_v` is `nL * GNsize` in CG operation, so it will run out of index range when GNsize > bsize.

it's initialized in 27th line in init_net.m:
```
net.idx_phiZ{m} = net.idx_phiZ{m}(:) + [0:nL*bsize-1]*dab;
```
I think maybe `bsize` should be `max(bsize, GNsize)`?

**Comment by ccwang123** [comment]
Thank you! It is fixed.
