### ISSUE TITLE
Project 6 profile viewer error on Dept 217 workstations

### ISSUE THREAD

**Issue by hyeong01** [cjlin1/simpleNN#14]
Whenever I try profiling on Matlab on Dept 217 workstations I encounter such error:

profile viewer
Error using profile (line 188)
The profiler requires the Java VM

I suspect this is because of path error since JVM is already installed. However, I cannot reset the path -- it is written in a read-only file.

I wonder how others profiled codes in MATLAB on the school server so far? 

The reason I did not encounter such a problem because I have been using MATLAB on windows so far, but for Project 6 I had to move to the workstations provided from the school because the memory requirement was too huge.

**Comment by hyeong01** [comment]
I solved this by sending the files to my local computer. Please comment me if you have better solutions! I will close the issue after a few days myself.

**Comment by jojo-kr** [comment]
Issue closed. Please refer to the comment above. The TA had the same solution.

**Comment by hyeong01** [comment]
Issue closed. Please refer to the comment above. The TA had the same solution.
